### PR TITLE
Lcb/edits001

### PR DESCRIPTION
**Pull request by brookslogan**
Midway through an editing pass.  As `epix_slide` pseudoprospective forecasts area already here, the additions I'm considering (if possible today) are (a) implementing & showing a way to read `epi_archive` from snapshot files, and (b) applying some epiprocess interface changes that are in the its `dev` branch or close to being merged there.

### CODE REVIEW

**Comment by brookslogan** [comment]
I keep on getting sidetracked by bugs in various packages, think will be the end of my edits for today unless you spot issues.

**Comment by brookslogan** [comment]
One potential issue: is the pages deployment action going to balk at this due to renv managing dependencies?  Or is it fine because we're already tracking the rendered files and don't need to re-render them?

**Comment by dajmcdon** [comment]
Shouldn't be a problem because we're rendering locally. If we want to eventually make this more reproducible, we can have CI build, but there the renv should help.

**Review by dajmcdon — APPROVED** [review]
@brookslogan everything looks good to me. We should update the readme as well before sharing.

**Pull request merged**
